trigger:
 branches:
  include:
    - "*"
  exclude:
    - main

variables:
  buildConfiguration: "Test"
  webRepository: "capstonefinal"
  tag: "$(Build.BuildId)"

stages:
  - stage: "Test"
    displayName: "Testing"
    jobs:
      - job: "Test"
        displayName: "Test Job"
        pool:
          vmImage: "ubuntu-20.04"
        steps:
          - task: CmdLine@2
            displayName: hadolint
            inputs:
              script: "cat $(Build.SourcesDirectory)/Dockerfile | docker run --rm -i -v $(Build.SourcesDirectory)/hadolint.yaml:/.config/hadolint.yaml hadolint/hadolint > $(Build.ArtifactStagingDirectory)/output.txt && cat $(Build.SourcesDirectory)/Dockerfile | docker run --rm -i -v $(Build.SourcesDirectory)/hadolint.yaml:/.config/hadolint.yaml hadolint/hadolint"
              workingDirectory: "$(Build.SourcesDirectory)"
            continueOnError: true
          - task: PythonScript@0
            inputs:
              script: |
               pip3 install bandit
               bandit -r $(Build.SourcesDirectory)/app.py -f json | tee $(Build.ArtifactStagingDirectory)/bandit-output.json
              

            
          - task: WhiteSource@21
            inputs:
              projectName: 'CapstoneFinal'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: $(Build.ArtifactStagingDirectory)
              artifactName: hadolintOutput
